version: "3.7"

services:
  shell:
    build:
      context: .
    restart: on-failure
    command: ["jekyll", "s", "--host=0.0.0.0"]
    ports:
      - 4000:4000
    working_dir: "/blog"
    volumes:
      - "./:/blog"
